name: Build Silvergun Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14
      - name: Build demo
      - run: sh build_emscripten.sh
